
package com.xjj.ws.sso;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SSOVerifyService", targetNamespace = "http://sso.ws.xjj.com/", wsdlLocation = "http://192.168.0.117:93/sso?wsdl")
@HandlerChain(file = "handler-chain.xml")
public class SSOVerifyService
    extends Service
{

    private final static URL SSOVERIFYSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.xjj.ws.sso.SSOVerifyService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.xjj.ws.sso.SSOVerifyService.class.getResource(".");
            url = new URL(baseUrl, "http://192.168.0.117:93/sso?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://192.168.0.117:93/sso?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SSOVERIFYSERVICE_WSDL_LOCATION = url;
    }

    public SSOVerifyService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }
    
    public SSOVerifyService(String ssourl) throws MalformedURLException {
    	super(new URL(ssourl),new QName("http://sso.ws.xjj.com/", "SSOVerifyService"));
    }

    public SSOVerifyService() {
        super(SSOVERIFYSERVICE_WSDL_LOCATION, new QName("http://sso.ws.xjj.com/", "SSOVerifyService"));
    }

    /**
     * 
     * @return
     *     returns SSOVerify
     */
    @WebEndpoint(name = "SSOVerifyPort")
    public SSOVerify getSSOVerifyPort() {
        return super.getPort(new QName("http://sso.ws.xjj.com/", "SSOVerifyPort"), SSOVerify.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SSOVerify
     */
    @WebEndpoint(name = "SSOVerifyPort")
    public SSOVerify getSSOVerifyPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://sso.ws.xjj.com/", "SSOVerifyPort"), SSOVerify.class, features);
    }

}
