
package com.xjj.ws.distribute;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "distribute", targetNamespace = "http://distribute.ws.xjj.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Distribute {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "orgDistribute", targetNamespace = "http://distribute.ws.xjj.com/", className = "com.xjj.ws.distribute.OrgDistribute")
    @ResponseWrapper(localName = "orgDistributeResponse", targetNamespace = "http://distribute.ws.xjj.com/", className = "com.xjj.ws.distribute.OrgDistributeResponse")
    public boolean orgDistribute(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "userDistribute", targetNamespace = "http://distribute.ws.xjj.com/", className = "com.xjj.ws.distribute.UserDistribute")
    @ResponseWrapper(localName = "userDistributeResponse", targetNamespace = "http://distribute.ws.xjj.com/", className = "com.xjj.ws.distribute.UserDistributeResponse")
    public boolean userDistribute(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
